language: node_js
notifications:
  email: false
node_js:
  - '8'
cache:
  npm: false
env:
  - TASK=lint
  - TASK=test
  - TASK=coverage
  - TASK=test:gas:ci
before_script:
  - npm prune
script: "npm run $TASK"
after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
