language: node_js
notifications:
  email: false
node_js:
  - '10'
cache:
  npm: false
before_install:
  - sudo apt-get install -y netcat
env:
  - TASK=test:gas:ci
script: "npm run $TASK"
after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
